#!/bin/bash

SERVER_PROPERTIES=server.properties
MINECRAFT_SERVER_JAR=forge-1.8-11.14.1.1397-universal.jar

cd $OPENSHIFT_DATA_DIR

if [ ! -e $MINECRAFT_SERVER_JAR ]; then
   wget http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.8-11.14.1.1397/forge-1.8-11.14.1.1397-universal.jar -O $MINECRAFT_SERVER_JAR
fi

if [ ! -e "$SERVER_PROPERTIES" ]; then
   erb $OPENSHIFT_REPO_DIR/${SERVER_PROPERTIES}.erb > $SERVER_PROPERTIES
fi 

echo 'Now, execute on your local machine and connect your minecraft client using given IP:PORT'
echo 
echo " $ rhc port-forward -a $OPENSHIFT_APP_NAME"

